### ISSUE TITLE
Chores: Deposition 10307

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal-backend#175]
Some refinements of deposition 10307 are pending: 

- [ ] Remove `"GO:0160201", "GO:0160202"` and polaroplast from validation exclude list pending availability through API (terms have been created https://github.com/geneontology/go-ontology/issues/28569 https://github.com/geneontology/go-ontology/issues/28570)
- [ ] Request  new terms for the structures described in the paper
- [ ] Add the final publication after peer-review
- [ ] Ingest other gain files pending https://github.com/chanzuckerberg/cryoet-data-portal/issues/947
- [ ] Use `state` instead of `description` field to describe sub-structures  pending https://github.com/chanzuckerberg/cryoet-data-portal/issues/946
